# lup: ignore[constant-declaration]
# Both constants here are this application's own composition — what its CLI
# declines from the library's roster, and which sub-apps only it has. A
# composition root is where a judgement is finally made rather than passed on,
# so there is no caller above it to take these from.
"""This application's sub-app roster: what it declines, and what only it has.

The library ships the whole roster and a project states its delta. That
direction matters: lup arrives through a lock refresh and the template through
a hand-replayed commit, so a sub-app added upstream reaches this project's
dependencies immediately and its ``--help`` never — and a restated roster that
fell behind is indistinguishable from a decision. Naming only what is declined
means a new sub-app arrives served, and an absent one was chosen.

Only specs here, never Typer apps. Documents under ``harness/content/``
describe this CLI and are themselves generated by it, so a roster that
imported those apps to learn their names would make the guidance depend on the
tooling that renders it. ``devtools/main.py`` is where each name meets the app
that answers to it, and nothing imports ``main``.
"""

from lup.adapters.claude.usage.reader import claude_usage_entry
from lup.adapters.codex.usage.reader import codex_usage_entry
from lup.devtools.roster import LIBRARY_SPECS
from lup.devtools.subapps import SubAppSelection, SubAppSpec
from lup.usage.app import UsageEntry

USAGE_ENTRIES: list[UsageEntry] = [claude_usage_entry(), codex_usage_entry()]
"""One entry per backend this project runs on, each reading its own account.

Declared here rather than at the composition root because which backends a
project runs on is the same kind of decision as which sub-apps it serves, and
this module is where the seam guard sanctions naming a concrete adapter.
"""

RETIRED = [
    # lup: defer[lup ships lup.devtools.dashboard assets in its wheel]: remount the
    # library's setup dashboard. It is dropped rather than broken: lup's
    # package-data never names that package, so the installed wheel has no
    # index.html and every request to `/` raises FileNotFoundError (issue #1). This
    # project serves its own setup and enrolment page at `forumboard serve`, which
    # covers the one integration it has, so nothing is missing meanwhile.
    "dashboard",
]
"""Library sub-apps this CLI does not serve."""

SELECTION = SubAppSelection(retired=RETIRED)
"""What this CLI keeps of the library's roster, as a delta rather than a copy."""

APPLICATION_SPECS = [
    SubAppSpec(name="agent", help="Agent introspection and debugging"),
    SubAppSpec(name="dev", help="Worktrees, branches, and pre-flight checks"),
    SubAppSpec(name="hooks", help="Query the permission policy"),
]
"""The sub-apps this application answers for itself.

``dev`` and ``hooks`` name entries the library also ships: each is declared
here because this project's version differs — ``dev`` mounts the initialization
and library trees beside the inherited gate, and ``hooks`` answers from the
``HookSet`` both generated plugins are compiled from. Declaring one replaces
the default rather than retiring it, so the name keeps its place in ``--help``.
"""

SUBAPP_SPECS = SELECTION.specs(LIBRARY_SPECS, APPLICATION_SPECS)
"""Every sub-app this CLI serves, in the order `--help` lists them."""
